services:
  spark-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-dev-container
    working_dir: /app
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    command: tail -f /dev/null