[project]
name = "lakehouse-from-scratch"
version = "0.1.0"
description = "Data Lakehouse Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.1",
    "pyspark==3.5.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "ruff>=0.12.7",
]
